### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by mguida22** [CUBigDataClass/Elections#6]
Something is crashing that makes the streams go down. I believe the `extract-tweets` python script has an unhandled exception but I'm not sure what causes it. I'll dig into it this weekend

**Comment by 719Ben** [comment]
We were getting an `AttributeError` when the type of the object was `None`. Not sure why it was happening, we need to look into it, but I just put a temp fix up.

**Comment by mguida22** [comment]
Take a look at https://github.com/tweepy/tweepy/issues/576. For now we can probably just pass on it, it's not a big deal to throw away a few tweets but hopefully there will be a fix soon for it

**Comment by mguida22** [comment]
I've been thinking this through and I think I have an idea. When we pass [here](https://github.com/CUBigDataClass/Elections/blob/master/extract.py#L38) on the `AttributeError` so the program doesn't crash, we need to kick off the stream again. The error causes the stream to stop and so it silently fails. I'll get a fix up for this soon
